export const MEDIA = {
  HTML_IMAGE: "HTML_IMAGE",
  HTML_IFRAME: "HTML_IFRAME",
  HTML_VIDEO: "HTML_VIDEO",
  PLANE_IMAGE: "PLANE_IMAGE",
  PLANE_VIDEO: "PLANE_VIDEO",
  MODAL: "MODAL",
  PLACEHOLDER_2D: "PLACEHOLDER_2D",
  PLACEHOLDER_3D: "PLACEHOLDER_3D",
};
